### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by arvid-r** [petriborg/Scons-Protoc#1]
Hi!
This is a useful piece of code. However, I see no license information. How can I use this code without feeling bad about it?

**Comment by petriborg** [comment]
Well, this code is obviously very old and unmaintained - [Scons-contrib](https://github.com/SCons/scons-contrib) also has protobuf integration for a long time now.

In any case, I'll assign a license.

See f95b46bf2b58d8b8c3484d4b1a935432e422dacd

**Comment by arvid-r** [comment]
Thanks! I'll go with the SCons-contrib version then. I'm not sure why I missed it in the first place ...
